name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Use server repository
        uses: actions/checkout@v2 
        with:
          repository: yale-swe/f23-here/server
          path: './server'
      - name: Install dependencies
        run: npm i
      - name: Build app
        run: npm run build --if-present
      - name: Run tests
        run: npm test
